#!/bin/bash

heading() {
    echo '----------------------------------'
    echo "> $@"
    echo '----------------------------------'
}

login() {
    ssh $user@$ip
}

restart_service() {
    $service_name=$1
    if [[ -z $service_name ]]; then
        read -p 'service to restart: ' service_name
    fi
    ssh -t $user@$ip "sudo systemctl restart $service_name"
}

reboot_server() {
    ssh -i $user@$ip 'sudo reboot'
}


show_usage() {
    cat <<help_message
server -- command for server maintanace

commands

    login
    restart [servicename]
    reboot

help_message
}


if [[ ! -f .env ]]; then
    echo 'It looks like you do not have a server setup yet, please'
    echo 'tun the setup script first.'
    exit 1
fi

source .env

command=$1
shift

case $command in
    login)
        login
        ;;
    restart)
        restart_service
        ;;
    reboot)
        reboot_server
        ;;
    *)
        show_usage
        ;;
esac
