#!/bin/bash

heading(){
    echo '----------------------------------'
    echo "> $@"
    echo '----------------------------------'
}

if [[ -e ./.env ]]; then
    echo 'It looks like things are already setup, aborting...'
    echo 'To redo the setup process, delete the ".env" file'
    exit 1
fi

# get relevant info
read -p 'Enter the servers ip address: ' ip
read -p "Enter a username (default $USER): " user
if [[ -z "$user" ]]; then
    user=$USER
fi

# set the admin password
echo
echo 'We are going to ask you for a password, this will be the password for'
echo 'administrative access on your server. Make sure this is a strong password!'
echo 'Make sure to remember this password.'
echo
read -sp 'Enter a password: ' password
echo
read -sp 'Confirm password: ' confirm_password
echo
if [[ "$password" != "$confirm_password" ]]; then
    echo 'passwords do not match!'
    exit 1
fi

# set database password
echo
echo 'We are going to ask for another password. This will be the password for'
echo 'administrative access to your database. Be sure to remember this one as'
echo 'well, and to choose a *strong* password.'
echo
read -sp 'Enter a password: ' db_password
echo
read -sp 'Confirm password: ' confirm_db_password
echo
echo
if [[ "$db_password" != "$confirm_db_password" ]]; then
    echo 'passwords do not match!'
    exit 1
fi

# create the .env file
cat > .env <<EOF
ip=$ip
user=$user
EOF

echo '".env" file created!'
echo
echo 'Since this will be the first time we will have connected to your server,'
echo 'you will be prompted whether or not you trust the server. Type yes when'
echo 'prompted.'
echo
read -p 'Press enter to continue and setup the server'

heading 'running provision script'

ssh root@$ip bash < provision.sh | tee provision.log

heading 'securing mysql installation...'

# secure the mysql install
ssh root@$ip 'mysql -u root' <<sql
CREATE USER $user@localhost IDENTIFIED BY '$db_password';
GRANT ALL ON *.* TO $user@localhost WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$db_password');
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
FLUSH PRIVILEGES;
sql

heading 'creating user'

ssh root@$ip bash <<setup_user
# create a user add add the ssh key
useradd --create-home --shell /bin/bash --groups sudo,tomcat $user
echo '$user:$password' | chpasswd
# copy over ssh key config for the new user
mkdir -p /home/$user/.ssh
cp \$HOME/.ssh/authorized_keys /home/$user/.ssh/
chown --recursive $user:$user /home/$user/.ssh

# disable password login + root login
perl -i -pe 's/(PasswordAuthentication\s*)yes/\1no/' /etc/ssh/sshd_config
perl -i -pe 's/(PermitRootLogin\s*)yes/\1no/' /etc/ssh/sshd_config
service sshd restart
service ssh restart
setup_user

heading 'all done!'
