#!/bin/bash

# find out where this script is located so we can be sure we're running
# everything from the correct location
SCRIPT_PATH=$0
while [[ -L $SCRIPT_PATH ]] ; do # resolve symlinks
	SCRIPT_PATH="$(readlink $SCRIPT_PATH)"
done
BASE_DIR="$( cd "$( dirname "$SCRIPT_PATH" )" && pwd )"

ENV_FILE="$BASE_DIR/.env"
TEMPLATES="$BASE_DIR/templates"
SCRIPTS="$BASE_DIR/scripts"
SNIPPETS="$SCRIPTS/snippets"
TESTS="$BASE_DIR/tests"

if [[ ! -f $ENV_FILE ]]; then
	echo 'No .env file found!'
	echo 'Currently we can only test everything with an already setup environment.'
	echo 'exiting...'
	exit 1
fi

source $ENV_FILE
source $SCRIPTS/util.sh

command=$1 ; shift

case $command in
	util) source $TESTS/util.sh;;
	site) source $TESTS/site.sh;;
	* ) echo 'util | site';;
esac

# # enable passwordless sudo
# # WE SHOULD BE VERY CAREFUL WITH THIS
# # that being said, this is probably the most sane way to preform automated
# # testing, as every command will prompt for a sudo password
# ssh $user@$ip "echo '$user ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo"
