#!/bin/bash

TESTS="$BASE_DIR/tests"

if [[ ! -f $ENV_FILE ]]; then
	echo 'No env file found!'
	echo 'Currently we can only test everything with an already setup environment.'
	echo 'exiting...'
	exit 1
fi

source $ENV_FILE
source $SCRIPTS/util.sh

command=$1 ; shift

case $command in
	util)  source $TESTS/util.sh;;
	site)  source $TESTS/site.sh;;
	setup) source $TESTS/setup.sh;;
	deploy) source $TESTS/deploy.sh;;
	_sudo)
		# Enable passwordless sudo
		# Intentionally undocumented, as we probably don't want end users doing
		# this, but for running the automated tests, this is the only sane way
		# to do things, as almost everything we want to test requires a sudo
		# password.
		ssh -t $user@$ip "echo '$user ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo"
		;;

	* ) echo 'util | site | setup | deploy';;
esac
