#!/bin/bash

# check for the utilities we'll need
prereqs=(dig ssh scp)
for tool in ${prereqs[@]}; do
    which $tool >/dev/null
    if [[ $? -ne 0 ]]; then
        echo "Please install '$tool' before continuing."
        exit 1
    fi
done

heading(){
    echo '----------------------------------'
    echo "> $@"
    echo '----------------------------------'
}

if [[ -e ./.env ]]; then
    echo 'It looks like things are already setup, aborting...'
    echo 'To redo the setup process, delete the ".env" file'
    exit 1
fi

read -p 'Enter the servers ip address: ' ip
echo
echo 'Since this will be the first time we will have connected to your server,'
echo 'you will be prompted whether or not you trust the server. Type yes when'
echo 'prompted.'
echo
# make sure we can access that server
ssh root@$ip ls > /dev/null
if [[ $? -ne 0 ]]; then
    echo "Cannot login to $ip!"
    exit 1
fi

read -p "Enter a username (default $USER): " user
if [[ -z "$user" ]]; then
    user=$USER
fi

echo
echo 'We will need an email address for obtaining a ssl certificate, while this'
echo 'is optional, it is recommended so that you can be contacted if anything'
echo 'goes wrong with your site.'
read -p 'email: ' email
echo

# set the admin password
echo
echo 'We are going to ask you for a password, this will be the password for'
echo 'administrative access on your server. Make sure this is a strong password!'
echo 'Make sure to remember this password.'
echo
read -sp 'Enter a password: ' password
echo
read -sp 'Confirm password: ' confirm_password
echo
if [[ "$password" != "$confirm_password" ]]; then
    echo 'passwords do not match!'
    exit 1
fi

# set database password
echo
echo 'We are going to ask for another password. This will be the password for'
echo 'administrative access to your database. Be sure to remember this one as'
echo 'well, and to choose a *strong* password.'
echo
read -sp 'Enter a password: ' db_password
echo
read -sp 'Confirm password: ' confirm_db_password
echo
echo
if [[ "$db_password" != "$confirm_db_password" ]]; then
    echo 'passwords do not match!'
    exit 1
fi

# create the .env file
cat > .env <<EOF
ip=$ip
user=$user
email=$email
EOF

echo '".env" file created!'
echo
read -p 'Press enter to continue and setup the server'

heading 'running provision script'

ssh root@$ip bash < provision.sh | tee provision.log

heading 'securing mysql installation...'

# secure the mysql install
ssh root@$ip 'mysql -u root' <<sql
CREATE USER $user@localhost IDENTIFIED BY '$db_password';
GRANT ALL ON *.* TO $user@localhost WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$db_password');
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';
FLUSH PRIVILEGES;
sql

heading 'creating user'

ssh root@$ip bash <<setup_user
# create a user add add the ssh key
useradd --create-home --shell /bin/bash --groups sudo,tomcat $user
echo '$user:$password' | chpasswd
# copy over ssh key config for the new user
mkdir -p /home/$user/.ssh
cp \$HOME/.ssh/authorized_keys /home/$user/.ssh/
chown --recursive $user:$user /home/$user/.ssh

# disable password login + root login
perl -i -pe 's/(PasswordAuthentication\s*)yes/\1no/' /etc/ssh/sshd_config
perl -i -pe 's/(PermitRootLogin\s*)yes/\1no/' /etc/ssh/sshd_config
service sshd restart
service ssh restart
setup_user

heading 'all done!'
